'use strict';

module.exports = {
  FIRST_PAGE: 1,
  CONTESTS_PER_PAGE: 20,
  RANK_BEST: 'BEST',
  RANK_LATEST: 'LATEST',
  RANK_RANDOM: 'RANDOM',
  CONTEST_WAITING: 'WAITING',
  CONTEST_RUNNING: 'RUNNING',
  CONTEST_FINISHED: 'FINISHED'
};